"""Ride

Revision ID: 0848ecf403a6
Revises: 7385baad30c5
Create Date: 2020-06-11 20:11:24.507428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0848ecf403a6'
down_revision = '7385baad30c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('from_location', sa.String(), nullable=True),
    sa.Column('to_location', sa.String(), nullable=True),
    sa.Column('ride_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car'], ['car.id'], ),
    sa.ForeignKeyConstraint(['driver'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coriders',
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coriders')
    op.drop_table('ride')
    # ### end Alembic commands ###
