"""empty message

Revision ID: 39851449b83b
Revises: 7040138f187f
Create Date: 2020-06-23 16:51:10.353837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39851449b83b'
down_revision = '7040138f187f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'language')
    # ### end Alembic commands ###
