"""empty message

Revision ID: 6bb341d2c782
Revises: b16e0fc36646
Create Date: 2020-06-19 17:42:39.889318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb341d2c782'
down_revision = 'b16e0fc36646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('user_posted', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'account', ['user_posted'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'user_posted')
    # ### end Alembic commands ###
