"""empty message

Revision ID: 7040138f187f
Revises: a086dcd6d188
Create Date: 2020-06-23 16:40:51.749438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7040138f187f'
down_revision = 'a086dcd6d188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('about_ride', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'about_ride')
    # ### end Alembic commands ###
