"""empty message

Revision ID: 7cde205ff39b
Revises: 39851449b83b
Create Date: 2020-06-23 17:30:26.125985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cde205ff39b'
down_revision = '39851449b83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'about_ride')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('about_ride', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
