"""empty message

Revision ID: a086dcd6d188
Revises: 6bb341d2c782
Create Date: 2020-06-19 17:45:53.873585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a086dcd6d188'
down_revision = '6bb341d2c782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('user_posted_username', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'account', ['user_posted_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'user_posted_username')
    # ### end Alembic commands ###
