"""empty message

Revision ID: a5371b9ba7c0
Revises: d65c425b99fe
Create Date: 2020-06-10 23:57:15.304846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5371b9ba7c0'
down_revision = 'd65c425b99fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('member_since_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'member_since_utc')
    # ### end Alembic commands ###
