"""empty message

Revision ID: ad444f98ecf5
Revises: 0848ecf403a6
Create Date: 2020-06-17 21:40:26.039230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad444f98ecf5'
down_revision = '0848ecf403a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('free_seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'free_seats')
    # ### end Alembic commands ###
