"""empty message

Revision ID: af481a64c41a
Revises: e25e21f179c7
Create Date: 2020-06-08 17:32:08.118796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af481a64c41a'
down_revision = 'e25e21f179c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_brand'), 'car', ['brand'], unique=False)
    op.create_index(op.f('ix_car_color'), 'car', ['color'], unique=False)
    op.create_index(op.f('ix_car_model'), 'car', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_model'), table_name='car')
    op.drop_index(op.f('ix_car_color'), table_name='car')
    op.drop_index(op.f('ix_car_brand'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
