"""empty message

Revision ID: d65c425b99fe
Revises: 67d95329de78
Create Date: 2020-06-09 12:23:24.684850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65c425b99fe'
down_revision = '67d95329de78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('about_me', sa.String(length=200), nullable=True))
    op.add_column('account', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'last_seen')
    op.drop_column('account', 'about_me')
    # ### end Alembic commands ###
